comment win test group

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -709,77 +709,77 @@ jobs:
   #         retry_wait_seconds: 5
   #         command: cd terraform/ec2/linux && terraform destroy --auto-approve
 
-  EC2WinIntegrationTest:
-    needs: [BuildMSI, GenerateTestMatrix]
-    name: 'EC2WinIntegrationTest'
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        arrays: ${{ fromJson(needs.GenerateTestMatrix.outputs.ec2_windows_matrix) }}
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
-          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
+  # EC2WinIntegrationTest:
+  #   needs: [BuildMSI, GenerateTestMatrix]
+  #   name: 'EC2WinIntegrationTest'
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arrays: ${{ fromJson(needs.GenerateTestMatrix.outputs.ec2_windows_matrix) }}
+  #   permissions:
+  #     id-token: write
+  #     contents: read
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
+  #         ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-          aws-region: us-west-2
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+  #         aws-region: us-west-2
 
-      - name: Cache if success
-        id: ec2-win-integration-test
-        uses: actions/cache@v3
-        with:
-          path: go.mod
-          key: ec2-win-integration-test-${{ github.sha }}-${{ matrix.arrays.os }}-${{ matrix.arrays.arc }}-${{ matrix.arrays.test_dir }}
+  #     - name: Cache if success
+  #       id: ec2-win-integration-test
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: go.mod
+  #         key: ec2-win-integration-test-${{ github.sha }}-${{ matrix.arrays.os }}-${{ matrix.arrays.arc }}-${{ matrix.arrays.test_dir }}
 
-      - name: Echo OS
-        run: echo run on ec2 instance os ${{ matrix.arrays.os }}
+  #     - name: Echo OS
+  #       run: echo run on ec2 instance os ${{ matrix.arrays.os }}
 
-      - name: Verify Terraform version
-        run: terraform --version
+  #     - name: Verify Terraform version
+  #       run: terraform --version
 
-        # nick-fields/retry@v2 starts at base dir
-      - name: Terraform apply
-        if: steps.ec2-win-integration-test.outputs.cache-hit != 'true'
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 3
-          timeout_minutes: 30
-          retry_wait_seconds: 5
-          command: |
-            cd terraform/ec2/win
-            terraform init
-            if terraform apply --auto-approve \
-            -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
-            -var="ssh_key_value=${PRIVATE_KEY}" -var="ssh_key_name=${KEY_NAME}" \
-            -var="test_name=${{ matrix.arrays.os }}" \
-            -var="cwa_github_sha=${GITHUB_SHA}" \
-            -var="test_dir=${{ matrix.arrays.test_dir }}" \
-            -var="ami=${{ matrix.arrays.ami }}" \
-            -var="github_test_repo=${{env.CWA_GITHUB_TEST_REPO_URL}}" \
-            -var="github_test_repo_branch=${{env.CWA_GITHUB_TEST_REPO_BRANCH}}" \
-            -var="cwa_github_sha=${GITHUB_SHA}" \
-            -var="s3_bucket=${S3_INTEGRATION_BUCKET}" ; then terraform destroy -auto-approve
-            else
-              terraform destroy -auto-approve && exit 1
-            fi
+  #       # nick-fields/retry@v2 starts at base dir
+  #     - name: Terraform apply
+  #       if: steps.ec2-win-integration-test.outputs.cache-hit != 'true'
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         max_attempts: 3
+  #         timeout_minutes: 30
+  #         retry_wait_seconds: 5
+  #         command: |
+  #           cd terraform/ec2/win
+  #           terraform init
+  #           if terraform apply --auto-approve \
+  #           -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
+  #           -var="ssh_key_value=${PRIVATE_KEY}" -var="ssh_key_name=${KEY_NAME}" \
+  #           -var="test_name=${{ matrix.arrays.os }}" \
+  #           -var="cwa_github_sha=${GITHUB_SHA}" \
+  #           -var="test_dir=${{ matrix.arrays.test_dir }}" \
+  #           -var="ami=${{ matrix.arrays.ami }}" \
+  #           -var="github_test_repo=${{env.CWA_GITHUB_TEST_REPO_URL}}" \
+  #           -var="github_test_repo_branch=${{env.CWA_GITHUB_TEST_REPO_BRANCH}}" \
+  #           -var="cwa_github_sha=${GITHUB_SHA}" \
+  #           -var="s3_bucket=${S3_INTEGRATION_BUCKET}" ; then terraform destroy -auto-approve
+  #           else
+  #             terraform destroy -auto-approve && exit 1
+  #           fi
 
-      #This is here just in case workflow cancel
-      - name: Terraform destroy
-        if: ${{ cancelled() || failure() }}
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 3
-          timeout_minutes: 8
-          retry_wait_seconds: 5
-          command: cd terraform/ec2/win && terraform destroy --auto-approve
+  #     #This is here just in case workflow cancel
+  #     - name: Terraform destroy
+  #       if: ${{ cancelled() || failure() }}
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         max_attempts: 3
+  #         timeout_minutes: 8
+  #         retry_wait_seconds: 5
+  #         command: cd terraform/ec2/win && terraform destroy --auto-approve
 
   # EC2DarwinIntegrationTest:
   #   needs: [MakeMacPkg, EC2LinuxIntegrationTest, GenerateTestMatrix]
