comment out destroy

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -776,7 +776,7 @@ jobs:
         if: steps.eks-ec2-integration-test.outputs.cache-hit != 'true'
         uses: nick-fields/retry@v2
         with:
-          max_attempts: 3
+          max_attempts: 1
           timeout_minutes: 60 # EKS takes about 20 minutes to spin up a cluster and service on the cluster
           retry_wait_seconds: 5
           command: |
@@ -787,32 +787,39 @@ jobs:
             fi
 
             terraform init
-            if terraform apply --auto-approve \
+            terraform apply --auto-approve \
               -var="test_dir=${{ matrix.arrays.test_dir }}"\
               -var="cwagent_image_repo=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_INTEGRATION_TEST_REPO }}" \
               -var="cwagent_image_tag=${{ github.sha }}" \
               -var="ami_type=${{ matrix.arrays.ami }}" \
               -var="instance_type=${{ matrix.arrays.instanceType }}" \
-              -var="k8s_version=${{ matrix.arrays.k8s_version }}"; then
-              terraform destroy -auto-approve
-            else
-              terraform destroy -auto-approve && exit 1
-            fi
-
-      - name: Terraform destroy
-        if: ${{ cancelled() || failure() }}
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 3
-          timeout_minutes: 8
-          retry_wait_seconds: 5
-          command: |
-            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
-              cd "${{ matrix.arrays.terraform_dir }}"
-            else
-              cd terraform/eks/daemon
-            fi
-            terraform destroy --auto-approve
+              -var="k8s_version=${{ matrix.arrays.k8s_version }}"
+#            if terraform apply --auto-approve \
+#              -var="test_dir=${{ matrix.arrays.test_dir }}"\
+#              -var="cwagent_image_repo=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_INTEGRATION_TEST_REPO }}" \
+#              -var="cwagent_image_tag=${{ github.sha }}" \
+#              -var="ami_type=${{ matrix.arrays.ami }}" \
+#              -var="instance_type=${{ matrix.arrays.instanceType }}" \
+#              -var="k8s_version=${{ matrix.arrays.k8s_version }}"; then
+#              terraform destroy -auto-approve
+#            else
+#              terraform destroy -auto-approve && exit 1
+#            fi
+#
+#      - name: Terraform destroy
+#        if: ${{ cancelled() || failure() }}
+#        uses: nick-fields/retry@v2
+#        with:
+#          max_attempts: 3
+#          timeout_minutes: 8
+#          retry_wait_seconds: 5
+#          command: |
+#            if [ "${{ matrix.arrays.terraform_dir }}" != "" ]; then
+#              cd "${{ matrix.arrays.terraform_dir }}"
+#            else
+#              cd terraform/eks/daemon
+#            fi
+#            terraform destroy --auto-approve
 
 #  EKSPrometheusIntegrationTest:
 #    name: 'EKSPrometheusIntegrationTest'
